<?xml version="1.0" encoding="utf-8"?><Database Name="QL_BaiHat" Class="DBBaiHatDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.tbl_Album" Member="tbl_Albums">
    <Type Name="tbl_Album">
      <Column Name="MaAlbum" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenAlbum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="AnhBia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tbl_Album_tbl_ChiTietAlbum" Member="tbl_ChiTietAlbums" ThisKey="MaAlbum" OtherKey="MaAB" Type="tbl_ChiTietAlbum" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TheLoai" Member="tbl_TheLoais">
    <Type Name="tbl_TheLoai">
      <Column Name="MaTheLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_TheLoai_tbl_BaiHat" Member="tbl_BaiHats" ThisKey="MaTheLoai" OtherKey="MaTL" Type="tbl_BaiHat" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_BaiHat" Member="tbl_BaiHats">
    <Type Name="tbl_BaiHat">
      <Column Name="MaBH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenBH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaNS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tbl_BaiHat_tbl_ChiTietAlbum" Member="tbl_ChiTietAlbums" ThisKey="MaBH" OtherKey="MaBH" Type="tbl_ChiTietAlbum" />
      <Association Name="tbl_TheLoai_tbl_BaiHat" Member="tbl_TheLoai" ThisKey="MaTL" OtherKey="MaTheLoai" Type="tbl_TheLoai" IsForeignKey="true" />
      <Association Name="tbl_NhacSi_tbl_BaiHat" Member="tbl_NhacSi" ThisKey="MaNS" OtherKey="MaNhacSi" Type="tbl_NhacSi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ChiTietAlbum" Member="tbl_ChiTietAlbums">
    <Type Name="tbl_ChiTietAlbum">
      <Column Name="MaAB" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaBH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="tbl_Album_tbl_ChiTietAlbum" Member="tbl_Album" ThisKey="MaAB" OtherKey="MaAlbum" Type="tbl_Album" IsForeignKey="true" />
      <Association Name="tbl_BaiHat_tbl_ChiTietAlbum" Member="tbl_BaiHat" ThisKey="MaBH" OtherKey="MaBH" Type="tbl_BaiHat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_NhacSi" Member="tbl_NhacSis">
    <Type Name="tbl_NhacSi">
      <Column Name="MaNhacSi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhacSi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Anh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tbl_NhacSi_tbl_BaiHat" Member="tbl_BaiHats" ThisKey="MaNhacSi" OtherKey="MaNS" Type="tbl_BaiHat" />
    </Type>
  </Table>
</Database>