<?xml version="1.0" encoding="utf-8"?><Database Name="QL_NhanSuN" Class="QL_NhanSuNDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.tbl_Deparment" Member="tbl_Deparments">
    <Type Name="tbl_Deparment">
      <Column Name="DeptId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_Deparment_tbl_Employee" Member="tbl_Employees" ThisKey="DeptId" OtherKey="DeptId" Type="tbl_Employee" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Employee" Member="tbl_Employees">
    <Type Name="tbl_Employee">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="DeptId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_Deparment_tbl_Employee" Member="tbl_Deparment" ThisKey="DeptId" OtherKey="DeptId" Type="tbl_Deparment" IsForeignKey="true" />
    </Type>
  </Table>
</Database>